name: Test-Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  create-file:
    runs-on: self-hosted

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v3

    - name: Erstelle Textdatei
      run: echo "Die Pipeline funktioniert" > pipeline_test.txt

    - name: Datei anzeigen
      run: type pipeline_test.txt
