name: Test-Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-node-script:
    runs-on: self-hosted  # Oder windows-latest, falls der Runner auf Windows läuft

    steps:
          
      # Schritt 3: Node.js-Skript ausführen
      - name: Node.js Skript ausführen
        run: node calc.js
