name: Test-Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-node-script:
    runs-on: self-hosted  # Oder windows-latest, falls der Runner auf Windows l채uft

    steps:

      - name: PowerShell Ausf체hrungsrichtlinie setzen
        run: | 
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        shell: powershell    
      # Schritt 3: Node.js-Skript ausf체hren
      - name: Node.js Skript ausf체hren
        run: node calc.js
